Simply put, your main objective for this coding challenge is to send an API request to a server, get the data, then build a solution after getting the data.

Here's the server address: https://ct-mock-tech-assessment.herokuapp.com/<br>

The data is a collection of partners who need to attend meetings within their respective countries. For each partner you will find first and last names, email addresses, country locations and dates of availability.

Your job is to  build an invitation list based on the data. An example solution would look like the following. Keep in mind this is an example and not the real solution.

<strong>THE FOLLOWING IS `ONLY` AN EXAMPLE.</strong>

In [1]:
# [   {   'attendeeCount': 12,
#         'attendees': [   'rketring@codingtemple.com',
#                          'mlacau@codingtemple.com',
#                          'eomersa@codingtemple.com',
#                          'ssheahan@codingtemple.com',
#                          'msoult@codingtemple.com',
#                          'bwatton@codingtemple.com',
#                          'afernadez@codingtemple.com',
#                          'mmottern@codingtemple.com',
#                          'pdougherty@codingtemple.com',
#                          'sbeemon@codingtemple.com',
#                          'mvirgel@codingtemple.com',
#                          'hpolitte@codingtemple.com'],
#         'name': 'United States',
#         'startDate': '2017-06-01'},
#     {   'attendeeCount': 12,
#         'attendees': [   'sterrence@codingtemple.com',
#                          'dpatnode@codingtemple.com',
#                          'pbertog@codingtemple.com',
#                          'rguldemond@codingtemple.com',
#                          'rfarlee@codingtemple.com',
#                          'mclawson@codingtemple.com',
#                          'mbottenfield@codingtemple.com',
#                          'akulju@codingtemple.com',
#                          'cscoby@codingtemple.com',
#                          'dsiebenthal@codingtemple.com',
#                          'mcrossen@codingtemple.com',
#                          'mkimble@codingtemple.com'],
#         'name': 'Ireland',
#         'startDate': '2017-06-04'},
#     {   'attendeeCount': 14,
#         'attendees': [   'oduttinger@codingtemple.com',
#                          'tzavesky@codingtemple.com',
#                          'alyme@codingtemple.com',
#                          'aferkovich@codingtemple.com',
#                          'cbrookhouse@codingtemple.com',
#                          'mselk@codingtemple.com',
#                          'amacneil@codingtemple.com',
#                          'jplants@codingtemple.com',
#                          'devora@codingtemple.com',
#                          'bcustis@codingtemple.com',
#                          'labbot@codingtemple.com',
#                          'civery@codingtemple.com',
#                          'jfavieri@codingtemple.com',
#                          'anickless@codingtemple.com'],
#         'name': 'Spain',
#         'startDate': '2017-05-03'},
#     {   'attendeeCount': 3,
#         'attendees': [   'ltoepperwein@codingtemple.com',
#                          'olavine@codingtemple.com',
#                          'ksinitiere@codingtemple.com'],
#         'name': 'Mexico',
#         'startDate': '2017-05-03'},
#     {   'attendeeCount': 3,
#         'attendees': [   'abending@codingtemple.com',
#                          'agewant@codingtemple.com',
#                          'mboyarski@codingtemple.com'],
#         'name': 'Canada',
#         'startDate': '2017-07-02'},
#     {   'attendeeCount': None,
#         'attendees': [],
#         'name': 'Singapore',
#         'startDate': '2017-06-15'},
#     {   'attendeeCount': None,
#         'attendees': [],
#         'name': 'Japan',
#         'startDate': '2017-06-27'},
#     {   'attendeeCount': 16,
#         'attendees': [   'arosentrater@codingtemple.com',
#                          'jgoettsche@codingtemple.com',
#                          'nbehal@codingtemple.com',
#                          'bkilcher@codingtemple.com',
#                          'ostutler@codingtemple.com',
#                          'emaohu@codingtemple.com',
#                          'jbattistoni@codingtemple.com',
#                          'ccoryea@codingtemple.com',
#                          'gcintron@codingtemple.com',
#                          'scorlett@codingtemple.com',
#                          'dallocca@codingtemple.com',
#                          'dneedler@codingtemple.com',
#                          'lsachez@codingtemple.com',
#                          'sszabo@codingtemple.com',
#                          'smaleck@codingtemple.com',
#                          'jholtrop@codingtemple.com'],
#         'name': 'United Kingdom',
#         'startDate': '2017-06-05'},
#     {   'attendeeCount': 5,
#         'attendees': [   'bdurke@codingtemple.com',
#                          'jtopp@codingtemple.com',
#                          'tpinela@codingtemple.com',
#                          'jdefore@codingtemple.com',
#                          'jmacareno@codingtemple.com'],
#         'name': 'France',
#         'startDate': '2017-06-18'}]

For each partner, you need to categorize them according to the country in which they must attend the meeting. Find a way to determine which availability dates work best for everyone in EACH country. If a date doesn't work for a specific partner, they simply will not be able to attend the meeting. 

<strong>The kicker</strong>: this meeting will last a total of two days. Because of this, you must find a RANGE of two dates that work best for everyone. For whichever two days work the best, only display the first date everyone can start.

<strong>When you've finished, send a POST request to the same API (Google how to do this!!!). If you get a server response code of 200, you were successful in building your solution. Otherwise, hit the drawing board and try again!</strong>

In [1]:
import requests as r # often requests is imported under the alias r

data = r.get('https://ct-mock-tech-assessment.herokuapp.com/')
data.status_code

200

In [13]:
import numpy as np
import re
import requests as r
import pandas as pd
data = r.get('https://ct-mock-tech-assessment.herokuapp.com')
data =  data.json
data()

{'partners': [{'availableDates': ['2017-05-19',
    '2017-05-20',
    '2017-05-21',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'rketring@codingtemple.com',
   'firstName': 'Rebbeca',
   'lastName': 'Ketring'},
  {'availableDates': ['2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'ccafaro@codingtemple.com',
   'firstName': 'Casey',
   'lastName': 'Cafaro'},
  {'availableDates': ['2017-05-18',
    '2017-05-20',
    '2017-05-21',
    '2017-05-22',
    '2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-31',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'mlacau@codingtemple.com',
   'firstName': 'Merilyn',
   'lastName': 'Lacau'},
  {'availableDates': ['2017-05-16',
    '2017-05-21',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'eomersa@codingtemple.com',
   'firstName': 'Ester',
   'lastName': 'Omersa'},
  {'availableDates': ['2017-05-18',
    '2017-05-22',
    '2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-05-31',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'ssheahan@codingtemple.com',
   'firstName': 'Shanna',
   'lastName': 'Sheahan'},
  {'availableDates': ['2017-05-16',
    '2017-05-18',
    '2017-05-19',
    '2017-05-20',
    '2017-05-22',
    '2017-05-23',
    '2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'msoult@codingtemple.com',
   'firstName': 'Melvin',
   'lastName': 'Soult'},
  {'availableDates': ['2017-05-22',
    '2017-05-23',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'bleeks@codingtemple.com',
   'firstName': 'Bong',
   'lastName': 'Leeks'},
  {'availableDates': ['2017-05-18',
    '2017-05-21',
    '2017-05-23',
    '2017-05-24',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'lsolid@codingtemple.com',
   'firstName': 'Luna',
   'lastName': 'Solid'},
  {'availableDates': ['2017-05-19',
    '2017-05-22',
    '2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'bwatton@codingtemple.com',
   'firstName': 'Britt',
   'lastName': 'Watton'},
  {'availableDates': ['2017-05-16',
    '2017-05-22',
    '2017-05-24',
    '2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'jmasher@codingtemple.com',
   'firstName': 'Jeremiah',
   'lastName': 'Masher'},
  {'availableDates': ['2017-05-19',
    '2017-05-24',
    '2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'afernadez@codingtemple.com',
   'firstName': 'Aaron',
   'lastName': 'Fernadez'},
  {'availableDates': ['2017-05-17',
    '2017-05-18',
    '2017-05-19',
    '2017-05-21',
    '2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-05-31',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03',
    '2017-06-06'],
   'country': 'United States',
   'email': 'mmottern@codingtemple.com',
   'firstName': 'Meta',
   'lastName': 'Mottern'},
  {'availableDates': ['2017-05-19',
    '2017-05-24',
    '2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'pdougherty@codingtemple.com',
   'firstName': 'Phung',
   'lastName': 'Dougherty'},
  {'availableDates': ['2017-05-24',
    '2017-05-28',
    '2017-05-29',
    '2017-06-01',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'sdegunya@codingtemple.com',
   'firstName': 'Suzan',
   'lastName': 'Degunya'},
  {'availableDates': ['2017-05-18',
    '2017-05-21',
    '2017-05-22',
    '2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03',
    '2017-06-08',
    '2017-06-09'],
   'country': 'United States',
   'email': 'sbeemon@codingtemple.com',
   'firstName': 'Shaunta',
   'lastName': 'Beemon'},
  {'availableDates': ['2017-05-16',
    '2017-05-19',
    '2017-05-21',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-06-02',
    '2017-06-03'],
   'country': 'United States',
   'email': 'mvirgel@codingtemple.com',
   'firstName': 'Maggie',
   'lastName': 'Virgel'},
  {'availableDates': ['2017-05-21', '2017-05-24', '2017-05-26', '2017-05-31'],
   'country': 'United States',
   'email': 'szenger@codingtemple.com',
   'firstName': 'Soraya',
   'lastName': 'Zenger'},
  {'availableDates': ['2017-05-21',
    '2017-05-22',
    '2017-05-23',
    '2017-05-31',
    '2017-06-01'],
   'country': 'United States',
   'email': 'jglosson@codingtemple.com',
   'firstName': 'Jude',
   'lastName': 'Glosson'},
  {'availableDates': ['2017-05-16',
    '2017-05-17',
    '2017-05-18',
    '2017-05-19',
    '2017-05-23',
    '2017-05-24',
    '2017-05-26',
    '2017-05-31',
    '2017-06-01',
    '2017-06-07'],
   'country': 'United States',
   'email': 'fcragin@codingtemple.com',
   'firstName': 'Felicita',
   'lastName': 'Cragin'},
  {'availableDates': ['2017-05-17',
    '2017-05-19',
    '2017-05-22',
    '2017-05-25',
    '2017-05-26'],
   'country': 'United States',
   'email': 'sdockal@codingtemple.com',
   'firstName': 'Shakita',
   'lastName': 'Dockal'},
  {'availableDates': ['2017-05-17',
    '2017-05-21',
    '2017-05-23',
    '2017-05-24',
    '2017-05-25',
    '2017-05-26',
    '2017-06-09'],
   'country': 'United States',
   'email': 'rbreznay@codingtemple.com',
   'firstName': 'Robbyn',
   'lastName': 'Breznay'},
  {'availableDates': ['2017-05-18', '2017-05-19', '2017-06-01'],
   'country': 'United States',
   'email': 'dbelgrave@codingtemple.com',
   'firstName': 'Donny',
   'lastName': 'Belgrave'},
  {'availableDates': ['2017-05-19', '2017-05-21', '2017-05-25', '2017-06-01'],
   'country': 'United States',
   'email': 'nkobbe@codingtemple.com',
   'firstName': 'Nada',
   'lastName': 'Kobbe'},
  {'availableDates': ['2017-05-18', '2017-05-21', '2017-05-30'],
   'country': 'United States',
   'email': 'sskinnen@codingtemple.com',
   'firstName': 'Stacy',
   'lastName': 'Skinnen'},
  {'availableDates': ['2017-05-18',
    '2017-05-24',
    '2017-05-26',
    '2017-05-31',
    '2017-06-08'],
   'country': 'United States',
   'email': 'lskeeters@codingtemple.com',
   'firstName': 'Lanie',
   'lastName': 'Skeeters'},
  {'availableDates': ['2017-05-18',
    '2017-05-19',
    '2017-05-24',
    '2017-05-25',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01'],
   'country': 'United States',
   'email': 'hpolitte@codingtemple.com',
   'firstName': 'Hans',
   'lastName': 'Politte'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-04',
    '2017-06-05'],
   'country': 'Ireland',
   'email': 'sterrence@codingtemple.com',
   'firstName': 'Santos',
   'lastName': 'Terrence'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-06',
    '2017-06-07'],
   'country': 'Ireland',
   'email': 'dpatnode@codingtemple.com',
   'firstName': 'Daniella',
   'lastName': 'Patnode'},
  {'availableDates': ['2017-05-24',
    '2017-05-25',
    '2017-05-27',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-08',
    '2017-06-14'],
   'country': 'Ireland',
   'email': 'enawwar@codingtemple.com',
   'firstName': 'Everette',
   'lastName': 'Nawwar'},
  {'availableDates': ['2017-05-25',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-06',
    '2017-06-08',
    '2017-06-15'],
   'country': 'Ireland',
   'email': 'pbertog@codingtemple.com',
   'firstName': 'Paola',
   'lastName': 'Bertog'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-07',
    '2017-06-11'],
   'country': 'Ireland',
   'email': 'rguldemond@codingtemple.com',
   'firstName': 'Riva',
   'lastName': 'Guldemond'},
  {'availableDates': ['2017-05-26',
    '2017-05-27',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-04',
    '2017-06-07',
    '2017-06-09',
    '2017-06-11'],
   'country': 'Ireland',
   'email': 'rfarlee@codingtemple.com',
   'firstName': 'Rosanne',
   'lastName': 'Farlee'},
  {'availableDates': ['2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-07',
    '2017-06-11',
    '2017-06-17'],
   'country': 'Ireland',
   'email': 'elaskin@codingtemple.com',
   'firstName': 'Elliot',
   'lastName': 'Laskin'},
  {'availableDates': ['2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-06',
    '2017-06-11'],
   'country': 'Ireland',
   'email': 'greif@codingtemple.com',
   'firstName': 'Geneva',
   'lastName': 'Reif'},
  {'availableDates': ['2017-05-24',
    '2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-09',
    '2017-06-11',
    '2017-06-16'],
   'country': 'Ireland',
   'email': 'mclawson@codingtemple.com',
   'firstName': 'Marva',
   'lastName': 'Clawson'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-04',
    '2017-06-05',
    '2017-06-06',
    '2017-06-08',
    '2017-06-09'],
   'country': 'Ireland',
   'email': 'mbottenfield@codingtemple.com',
   'firstName': 'Marie',
   'lastName': 'Bottenfield'},
  {'availableDates': ['2017-05-26',
    '2017-05-27',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-07',
    '2017-06-09'],
   'country': 'Ireland',
   'email': 'akulju@codingtemple.com',
   'firstName': 'Ali',
   'lastName': 'Kulju'},
  {'availableDates': ['2017-05-24',
    '2017-05-25',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-04',
    '2017-06-05',
    '2017-06-08',
    '2017-06-11'],
   'country': 'Ireland',
   'email': 'cscoby@codingtemple.com',
   'firstName': 'Claude',
   'lastName': 'Scoby'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-11',
    '2017-06-17'],
   'country': 'Ireland',
   'email': 'dsiebenthal@codingtemple.com',
   'firstName': 'Dot',
   'lastName': 'Siebenthal'},
  {'availableDates': ['2017-05-26',
    '2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-06',
    '2017-06-07',
    '2017-06-09',
    '2017-06-11'],
   'country': 'Ireland',
   'email': 'dharriet@codingtemple.com',
   'firstName': 'Dina',
   'lastName': 'Harriet'},
  {'availableDates': ['2017-05-28',
    '2017-05-29',
    '2017-05-30',
    '2017-05-31',
    '2017-06-01',
    '2017-06-04',
    '2017-06-05',
    '2017-06-07'],
   'country': 'Ireland',
   'email': 'mcrossen@codingtemple.com',
   'firstName': 'Marget',
   'lastName': 'Crossen'},
  {'availableDates': ['2017-05-24', '2017-06-01', '2017-06-04', '2017-06-11'],
   'country': 'Ireland',
   'email': 'emullahy@codingtemple.com',
   'firstName': 'Edith',
   'lastName': 'Mullahy'},
  {'availableDates': ['2017-05-24',
    '2017-06-01',
    '2017-06-04',
    '2017-06-05',
    '2017-06-07',
    '2017-06-09'],
   'country': 'Ireland',
   'email': 'mkimble@codingtemple.com',
   'firstName': 'Marinda',
   'lastName': 'Kimble'},
  {'availableDates': ['2017-05-26', '2017-06-04', '2017-06-07', '2017-06-11'],
   'country': 'Ireland',
   'email': 'mcodispoti@codingtemple.com',
   'firstName': 'Marjorie',
   'lastName': 'Codispoti'},
  {'availableDates': ['2017-05-25', '2017-06-05'],
   'country': 'Ireland',
   'email': 'mdolinsky@codingtemple.com',
   'firstName': 'Margarita',
   'lastName': 'Dolinsky'},
  {'availableDates': ['2017-05-25', '2017-05-26', '2017-06-01', '2017-06-11'],
   'country': 'Ireland',
   'email': 'jlehoullier@codingtemple.com',
   'firstName': 'Jerrod',
   'lastName': 'Lehoullier'},
  {'availableDates': ['2017-05-27', '2017-06-01', '2017-06-07'],
   'country': 'Ireland',
   'email': 'jmanoso@codingtemple.com',
   'firstName': 'Jerrica',
   'lastName': 'Manoso'},
  {'availableDates': ['2017-05-24', '2017-05-26', '2017-06-05', '2017-06-11'],
   'country': 'Ireland',
   'email': 'mcomer@codingtemple.com',
   'firstName': 'Maryland',
   'lastName': 'Comer'},
  {'availableDates': ['2017-06-05', '2017-06-06', '2017-06-07'],
   'country': 'Ireland',
   'email': 'apassi@codingtemple.com',
   'firstName': 'Agripina',
   'lastName': 'Passi'},
  {'availableDates': ['2017-05-26',
    '2017-06-05',
    '2017-06-07',
    '2017-06-11',
    '2017-06-14'],
   'country': 'Ireland',
   'email': 'dtighe@codingtemple.com',
   'firstName': 'Delmer',
   'lastName': 'Tighe'},
  {'availableDates': ['2017-05-24', '2017-06-01'],
   'country': 'Ireland',
   'email': 'kdickinson@codingtemple.com',
   'firstName': 'Keisha',
   'lastName': 'Dickinson'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-23',
    '2017-04-24',
    '2017-04-26',
    '2017-04-27',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'oduttinger@codingtemple.com',
   'firstName': 'Obdulia',
   'lastName': 'Duttinger'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-28',
    '2017-05-01',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'tzavesky@codingtemple.com',
   'firstName': 'Twila',
   'lastName': 'Zavesky'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-19',
    '2017-04-23',
    '2017-04-26',
    '2017-04-27',
    '2017-04-28',
    '2017-04-29',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'alyme@codingtemple.com',
   'firstName': 'Antonina',
   'lastName': 'Lyme'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-24',
    '2017-04-25',
    '2017-04-27',
    '2017-04-29',
    '2017-04-30',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'mtalton@codingtemple.com',
   'firstName': 'Mechelle',
   'lastName': 'Talton'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-23',
    '2017-04-28',
    '2017-04-29',
    '2017-05-01',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'aferkovich@codingtemple.com',
   'firstName': 'Alleen',
   'lastName': 'Ferkovich'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-23',
    '2017-04-24',
    '2017-04-28',
    '2017-04-29',
    '2017-05-03',
    '2017-05-04',
    '2017-05-06'],
   'country': 'Spain',
   'email': 'cbrookhouse@codingtemple.com',
   'firstName': 'Caprice',
   'lastName': 'Brookhouse'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-23',
    '2017-04-27',
    '2017-04-29',
    '2017-04-30',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'mselk@codingtemple.com',
   'firstName': 'Marcela',
   'lastName': 'Selk'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-19',
    '2017-04-20',
    '2017-04-27',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'amacneil@codingtemple.com',
   'firstName': 'Allena',
   'lastName': 'Macneil'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-23',
    '2017-04-24',
    '2017-04-26',
    '2017-05-01',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'jplants@codingtemple.com',
   'firstName': 'Jen',
   'lastName': 'Plants'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04',
    '2017-05-08'],
   'country': 'Spain',
   'email': 'devora@codingtemple.com',
   'firstName': 'Dick',
   'lastName': 'Evora'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-22',
    '2017-04-23',
    '2017-04-24',
    '2017-04-28',
    '2017-04-29',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'bcustis@codingtemple.com',
   'firstName': 'Bronwyn',
   'lastName': 'Custis'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-26',
    '2017-04-27',
    '2017-04-29',
    '2017-04-30',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'labbot@codingtemple.com',
   'firstName': 'Loree',
   'lastName': 'Abbot'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-21',
    '2017-04-22',
    '2017-04-23',
    '2017-04-26',
    '2017-04-29',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'oalampi@codingtemple.com',
   'firstName': 'Otha',
   'lastName': 'Alampi'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-19',
    '2017-04-23',
    '2017-04-27',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04',
    '2017-05-08'],
   'country': 'Spain',
   'email': 'vodien@codingtemple.com',
   'firstName': 'Venus',
   'lastName': 'Odien'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-27',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'alema@codingtemple.com',
   'firstName': 'Angelita',
   'lastName': 'Lema'},
  {'availableDates': ['2017-04-15',
    '2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-24',
    '2017-04-29',
    '2017-05-01',
    '2017-05-02',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'civery@codingtemple.com',
   'firstName': 'Camie',
   'lastName': 'Ivery'},
  {'availableDates': ['2017-04-16',
    '2017-04-17',
    '2017-04-18',
    '2017-04-27',
    '2017-04-28',
    '2017-05-03',
    '2017-05-04'],
   'country': 'Spain',
   'email': 'dheckler@codingtemple.com',
   'firstName': 'Dorie',
   'lastName': 'Heckler'},
  {'availableDates': ['2017-05-07'],
   'country': 'Spain',
   'email': 'sloux@codingtemple.com',
   'firstName': 'Shayne',
   'lastName': 'Loux'},
  {'availableDates': ['2017-04-19',
    '2017-04-20',
    '2017-04-21',
    '2017-04-23',
    '2017-04-24',
    '2017-04-26',
    '2017-04-29'],
   'country': 'Spain',
   'email': 'npleasanton@codingtemple.com',
   'firstName': 'Nenita',
   'lastName': 'Pleasanton'},
  {'availableDates': ['2017-04-18',
    '2017-04-24',
    '2017-04-25',
    '2017-04-28',
    '2017-04-29'],
   'country': 'Spain',
   'email': 'bmcgue@codingtemple.com',
   'firstName': 'Blake',
   'lastName': 'Mcgue'},
  {'availableDates': ['2017-04-21',
    '2017-04-22',
    '2017-04-24',
    '2017-04-27',
    '2017-04-29',
    '2017-05-02',
    '2017-05-06'],
   'country': 'Spain',
   'email': 'cwalbright@codingtemple.com',
   'firstName': 'Caprice',
   'lastName': 'Walbright'},
  {'availableDates': ['2017-04-24', '2017-04-26'],
   'country': 'Spain',
   'email': 'lhalmstead@codingtemple.com',
   'firstName': 'Latrice',
   'lastName': 'Halmstead'},
  {'availableDates': ['2017-04-15',
    '2017-04-18',
    '2017-04-23',
    '2017-04-26',
    '2017-04-28',
    '2017-05-01',
    '2017-05-02',

In [21]:
df = pd.read_csv('./jsontocsv.csv')
df

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

,partners/availableDates/0,partners/availableDates/1,partners/availableDates/2,partners/availableDates/3,partners/availableDates/4,partners/availableDates/5,partners/availableDates/6,partners/availableDates/7,partners/availableDates/8,partners/country,partners/email,partners/firstName,partners/lastName,partners/availableDates/9,partners/availableDates/10,partners/availableDates/11,partners/availableDates/12
0,2017-05-19,2017-05-20,2017-05-21,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,rketring@codingtemple.com,Rebbeca,Ketring,NaN,NaN,NaN,NaN
1,2017-05-25,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-02,2017-06-03,NaN,NaN,United States,ccafaro@codingtemple.com,Casey,Cafaro,NaN,NaN,NaN,NaN
2,2017-05-18,2017-05-20,2017-05-21,2017-05-22,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-31,United States,mlacau@codingtemple.com,Merilyn,Lacau,2017-06-01,2017-06-02,2017-06-03,NaN
3,2017-05-16,2017-05-21,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,NaN,NaN,United States,eomersa@codingtemple.com,Ester,Omersa,NaN,NaN,NaN,NaN
4,2017-05-18,2017-05-22,2017-05-25,2017-05-28,2017-05-29,2017-05-31,2017-06-01,2017-06-02,2017-06-03,United States,ssheahan@codingtemple.com,Shanna,Sheahan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,2017-06-06,2017-06-13,2017-06-17,2017-06-20,2017-06-25,NaN,NaN,NaN,NaN,France,awaloven@codingtemple.com,Andrew,Waloven,NaN,NaN,NaN,NaN
229,2017-06-06,2017-06-11,2017-06-18,2017-06-19,2017-06-25,NaN,NaN,NaN,NaN,France,ssteffey@codingtemple.com,Sam,Steffey,NaN,NaN,NaN,NaN
230,2017-06-06,2017-06-11,2017-06-13,2017-06-15,2017-06-16,2017-06-18,2017-06-24,2017-06-25,NaN,France,lhaymer@codingtemple.com,Latrisha,Haymer,NaN,NaN,NaN,NaN
231,2017-06-06,2017-06-14,2017-06-16,2017-06-19,2017-06-25,NaN,NaN,NaN,NaN,France,hscheiern@codingtemple.com,Hassan,Scheiern,NaN,NaN,NaN,NaN
232,2017-06-05,2017-06-06,2017-06-12,2017-06-13,2017-06-16,2017-06-17,2017-06-25,NaN,NaN,France,bmerrithew@codingtemple.com,Benton,Merrithew,NaN,NaN,NaN,NaN

In [31]:
df.groupby('partners/availableDates/0').filter(lambda y: y.index.is_unique)

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:635: RuntimeWarning: divide by zero encountered in log
  do_groupsort = count > 0 and ((alpha + beta * ngroups) < (count * np.log(count)))
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:635: RuntimeWarning: divide by zero encountered in double_scalars
  do_groupsort = count > 0 and ((alpha + beta * ngroups) < (count * np.log(count)))
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:161: RuntimeWarning: divide by zero encountered in multiply
  out = stride * labels[0].astype("i8", subok=False, copy=False)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:171: RuntimeWarning: divide by zero encountered in equal
  mask = labels[0] == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:583: RuntimeWarning: divide by zero encountered in equal
  if np.all(group_index == -1):
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:635: RuntimeWarning: divide by zero encountered in multiply
  do_groupsort = count > 0 and ((alpha + beta * ngroups) < (count * np.log(count)))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

,partners/availableDates/0,partners/availableDates/1,partners/availableDates/2,partners/availableDates/3,partners/availableDates/4,partners/availableDates/5,partners/availableDates/6,partners/availableDates/7,partners/availableDates/8,partners/country,partners/email,partners/firstName,partners/lastName,partners/availableDates/9,partners/availableDates/10,partners/availableDates/11,partners/availableDates/12
0,2017-05-19,2017-05-20,2017-05-21,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,rketring@codingtemple.com,Rebbeca,Ketring,NaN,NaN,NaN,NaN
1,2017-05-25,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-02,2017-06-03,NaN,NaN,United States,ccafaro@codingtemple.com,Casey,Cafaro,NaN,NaN,NaN,NaN
2,2017-05-18,2017-05-20,2017-05-21,2017-05-22,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-31,United States,mlacau@codingtemple.com,Merilyn,Lacau,2017-06-01,2017-06-02,2017-06-03,NaN
3,2017-05-16,2017-05-21,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,NaN,NaN,United States,eomersa@codingtemple.com,Ester,Omersa,NaN,NaN,NaN,NaN
4,2017-05-18,2017-05-22,2017-05-25,2017-05-28,2017-05-29,2017-05-31,2017-06-01,2017-06-02,2017-06-03,United States,ssheahan@codingtemple.com,Shanna,Sheahan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,2017-06-06,2017-06-13,2017-06-17,2017-06-20,2017-06-25,NaN,NaN,NaN,NaN,France,awaloven@codingtemple.com,Andrew,Waloven,NaN,NaN,NaN,NaN
229,2017-06-06,2017-06-11,2017-06-18,2017-06-19,2017-06-25,NaN,NaN,NaN,NaN,France,ssteffey@codingtemple.com,Sam,Steffey,NaN,NaN,NaN,NaN
230,2017-06-06,2017-06-11,2017-06-13,2017-06-15,2017-06-16,2017-06-18,2017-06-24,2017-06-25,NaN,France,lhaymer@codingtemple.com,Latrisha,Haymer,NaN,NaN,NaN,NaN
231,2017-06-06,2017-06-14,2017-06-16,2017-06-19,2017-06-25,NaN,NaN,NaN,NaN,France,hscheiern@codingtemple.com,Hassan,Scheiern,NaN,NaN,NaN,NaN
232,2017-06-05,2017-06-06,2017-06-12,2017-06-13,2017-06-16,2017-06-17,2017-06-25,NaN,NaN,France,bmerrithew@codingtemple.com,Benton,Merrithew,NaN,NaN,NaN,NaN

In [27]:
country = df[df['partners/availableDates/0']=='2017-05-19']
country

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

,partners/availableDates/0,partners/availableDates/1,partners/availableDates/2,partners/availableDates/3,partners/availableDates/4,partners/availableDates/5,partners/availableDates/6,partners/availableDates/7,partners/availableDates/8,partners/country,partners/email,partners/firstName,partners/lastName,partners/availableDates/9,partners/availableDates/10,partners/availableDates/11,partners/availableDates/12
0,2017-05-19,2017-05-20,2017-05-21,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,rketring@codingtemple.com,Rebbeca,Ketring,NaN,NaN,NaN,NaN
8,2017-05-19,2017-05-22,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,United States,bwatton@codingtemple.com,Britt,Watton,2017-06-02,2017-06-03,NaN,NaN
10,2017-05-19,2017-05-24,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,United States,afernadez@codingtemple.com,Aaron,Fernadez,NaN,NaN,NaN,NaN
12,2017-05-19,2017-05-24,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,pdougherty@codingtemple.com,Phung,Dougherty,NaN,NaN,NaN,NaN
22,2017-05-19,2017-05-21,2017-05-25,2017-06-01,NaN,NaN,NaN,NaN,NaN,United States,nkobbe@codingtemple.com,Nada,Kobbe,NaN,NaN,NaN,NaN

In [45]:
sorted = df.groupby(['partners/availableDates/0','partners/firstName', 'partners/lastName', 'partners/email'])['partners/country'].apply(list).to_dict()
sorted

{('2017-04-15',
  'Alleen',
  'Ferkovich',
  'aferkovich@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Camie', 'Ivery', 'civery@codingtemple.com'): ['Spain'],
 ('2017-04-15',
  'Caprice',
  'Brookhouse',
  'cbrookhouse@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Dick', 'Evora', 'devora@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Jenee', 'Favieri', 'jfavieri@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Loree', 'Abbot', 'labbot@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Marcela', 'Selk', 'mselk@codingtemple.com'): ['Spain'],
 ('2017-04-15',
  'Obdulia',
  'Duttinger',
  'oduttinger@codingtemple.com'): ['Spain'],
 ('2017-04-15', 'Sima', 'Studniarz', 'sstudniarz@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Allena', 'Macneil', 'amacneil@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Angelita', 'Lema', 'alema@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Antonina', 'Lyme', 'alyme@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Bronwyn', 'Custis', 'bcustis@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Dorie', 'Heckler', 'dheckler@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Jen', 'Plants', 'jplants@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Mechelle', 'Talton', 'mtalton@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Otha', 'Alampi', 'oalampi@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Twila', 'Zavesky', 'tzavesky@codingtemple.com'): ['Spain'],
 ('2017-04-16', 'Venus', 'Odien', 'vodien@codingtemple.com'): ['Spain'],
 ('2017-04-17', 'Alfonso', 'Danza', 'adanza@codingtemple.com'): ['Mexico'],
 ('2017-04-17', 'Artie', 'Molinini', 'amolinini@codingtemple.com'): ['Mexico'],
 ('2017-04-17',
  'Billie',
  'Reatherford',
  'breatherford@codingtemple.com'): ['Mexico'],
 ('2017-04-17', 'Bobbie', 'Parmele', 'bparmele@codingtemple.com'): ['Mexico'],
 ('2017-04-17', 'Celine', 'Vipond', 'cvipond@codingtemple.com'): ['Mexico'],
 ('2017-04-17', 'Florencia', 'Maier', 'fmaier@codingtemple.com'): ['Mexico'],
 ('2017-04-17',
  'Olivia',
  'Treworgy',
  'otreworgy@codingtemple.com'): ['Mexico'],
 ('2017-04-17',
  'Paulina',
  'Strohbehn',
  'pstrohbehn@codingtemple.com'): ['Mexico'],
 ('2017-04-17',
  'Sharon',
  'Brugliera',
  'sbrugliera@codingtemple.com'): ['Mexico'],
 ('2017-04-18', 'Blake', 'Mcgue', 'bmcgue@codingtemple.com'): ['Spain'],
 ('2017-04-18',
  'Lazaro',
  'Toepperwein',
  'ltoepperwein@codingtemple.com'): ['Mexico'],
 ('2017-04-18', 'Otilia', 'Hindman', 'ohindman@codingtemple.com'): ['Spain'],
 ('2017-04-18',
  'Sara',
  'Vecchione',
  'svecchione@codingtemple.com'): ['Mexico'],
 ('2017-04-19',
  'Bobby',
  'Kuligowski',
  'bkuligowski@codingtemple.com'): ['Mexico'],
 ('2017-04-19',
  'Cameron',
  'Rupprecht',
  'crupprecht@codingtemple.com'): ['Mexico'],
 ('2017-04-19', 'Florene', 'Aceveda', 'faceveda@codingtemple.com'): ['Mexico'],
 ('2017-04-19', 'Glennie', 'Hilkert', 'ghilkert@codingtemple.com'): ['Mexico'],
 ('2017-04-19', 'Merissa', 'Delarme', 'mdelarme@codingtemple.com'): ['Mexico'],
 ('2017-04-19',
  'Nenita',
  'Pleasanton',
  'npleasanton@codingtemple.com'): ['Spain'],
 ('2017-04-19', 'Toni', 'Riopel', 'triopel@codingtemple.com'): ['Mexico'],
 ('2017-04-19',
  'Vonnie',
  'Chenevert',
  'vchenevert@codingtemple.com'): ['Mexico'],
 ('2017-04-19',
  'Youlanda',
  'Mikhaiel',
  'ymikhaiel@codingtemple.com'): ['Mexico'],
 ('2017-04-21',
  'Caprice',
  'Walbright',
  'cwalbright@codingtemple.com'): ['Spain'],
 ('2017-04-21', 'Ken', 'Scarboro', 'kscarboro@codingtemple.com'): ['Mexico'],
 ('2017-04-23',
  'Kathrin',
  'Sinitiere',
  'ksinitiere@codingtemple.com'): ['Mexico'],
 ('2017-04-24',
  'Jodee',
  'Iacobelli',
  'jiacobelli@codingtemple.com'): ['Mexico'],
 ('2017-04-24',
  'Latrice',
  'Halmstead',
  'lhalmstead@codingtemple.com'): ['Spain'],
 ('2017-04-25', 'Sean', 'Johannes', 'sjohannes@codingtemple.com'): ['Mexico'],
 ('2017-04-27', 'Shamika', 'Kampa', 'skampa@codingtemple.com'): ['Spain'],
 ('2017-04-28',
  'Adriane',
  'Nickless',
  'anickless@codingtemple.com'): ['Spain'],
 ('2017-04-28',
  'Floria',
  'Hurlebaus',
  'fhurlebaus@codingtemple.com'): ['Mexico'],
 ('2017-04-28', 'Olinda', 'Lavine', 'olavine@codingtemple.com'): ['Mexico'],
 ('2017-05-07', 'Shayne', 'Loux', 'sloux@codingtemple.com'): ['Spain'],
 ('2017-05-16',
  'Ester',
  'Omersa',
  'eomersa@codingtemple.com'): ['United States'],
 ('2017-05-16',
  'Felicita',
  'Cragin',
  'fcragin@codingtemple.com'): ['United States'],
 ('2017-05-16',
  'Jeremiah',
  'Masher',
  'jmasher@codingtemple.com'): ['United States'],
 ('2017-05-16',
  'Maggie',
  'Virgel',
  'mvirgel@codingtemple.com'): ['United States'],
 ('2017-05-16',
  'Melvin',
  'Soult',
  'msoult@codingtemple.com'): ['United States'],
 ('2017-05-17',
  'Meta',
  'Mottern',
  'mmottern@codingtemple.com'): ['United States'],
 ('2017-05-17',
  'Robbyn',
  'Breznay',
  'rbreznay@codingtemple.com'): ['United States'],
 ('2017-05-17',
  'Shakita',
  'Dockal',
  'sdockal@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Donny',
  'Belgrave',
  'dbelgrave@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Hans',
  'Politte',
  'hpolitte@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Lanie',
  'Skeeters',
  'lskeeters@codingtemple.com'): ['United States'],
 ('2017-05-18', 'Luna', 'Solid', 'lsolid@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Merilyn',
  'Lacau',
  'mlacau@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Shanna',
  'Sheahan',
  'ssheahan@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Shaunta',
  'Beemon',
  'sbeemon@codingtemple.com'): ['United States'],
 ('2017-05-18',
  'Stacy',
  'Skinnen',
  'sskinnen@codingtemple.com'): ['United States'],
 ('2017-05-19',
  'Aaron',
  'Fernadez',
  'afernadez@codingtemple.com'): ['United States'],
 ('2017-05-19',
  'Britt',
  'Watton',
  'bwatton@codingtemple.com'): ['United States'],
 ('2017-05-19', 'Nada', 'Kobbe', 'nkobbe@codingtemple.com'): ['United States'],
 ('2017-05-19',
  'Phung',
  'Dougherty',
  'pdougherty@codingtemple.com'): ['United States'],
 ('2017-05-19',
  'Rebbeca',
  'Ketring',
  'rketring@codingtemple.com'): ['United States'],
 ('2017-05-21',
  'Jude',
  'Glosson',
  'jglosson@codingtemple.com'): ['United States'],
 ('2017-05-21',
  'Soraya',
  'Zenger',
  'szenger@codingtemple.com'): ['United States'],
 ('2017-05-22', 'Bong', 'Leeks', 'bleeks@codingtemple.com'): ['United States'],
 ('2017-05-24', 'Claude', 'Scoby', 'cscoby@codingtemple.com'): ['Ireland'],
 ('2017-05-24', 'Edith', 'Mullahy', 'emullahy@codingtemple.com'): ['Ireland'],
 ('2017-05-24', 'Everette', 'Nawwar', 'enawwar@codingtemple.com'): ['Ireland'],
 ('2017-05-24',
  'Keisha',
  'Dickinson',
  'kdickinson@codingtemple.com'): ['Ireland'],
 ('2017-05-24', 'Marinda', 'Kimble', 'mkimble@codingtemple.com'): ['Ireland'],
 ('2017-05-24', 'Marva', 'Clawson', 'mclawson@codingtemple.com'): ['Ireland'],
 ('2017-05-24', 'Maryland', 'Comer', 'mcomer@codingtemple.com'): ['Ireland'],
 ('2017-05-24',
  'Suzan',
  'Degunya',
  'sdegunya@codingtemple.com'): ['United States'],
 ('2017-05-25',
  'Casey',
  'Cafaro',
  'ccafaro@codingtemple.com'): ['United States'],
 ('2017-05-25',
  'Jerrod',
  'Lehoullier',
  'jlehoullier@codingtemple.com'): ['Ireland'],
 ('2017-05-25',
  'Margarita',
  'Dolinsky',
  'mdolinsky@codingtemple.com'): ['Ireland'],
 ('2017-05-25', 'Paola', 'Bertog', 'pbertog@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Ali', 'Kulju', 'akulju@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Delmer', 'Tighe', 'dtighe@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Dina', 'Harriet', 'dharriet@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Elliot', 'Laskin', 'elaskin@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Geneva', 'Reif', 'greif@codingtemple.com'): ['Ireland'],
 ('2017-05-26',
  'Marjorie',
  'Codispoti',
  'mcodispoti@codingtemple.com'): ['Ireland'],
 ('2017-05-26', 'Rosanne', 'Farlee', 'rfarlee@codingtemple.com'): ['Ireland'],
 ('2017-05-27', 'Jerrica', 'Manoso', 'jmanoso@codingtemple.com'): ['Ireland'],
 ('2017-05-28',
  'Daniella',
  'Patnode',
  'dpatnode@codingtemple.com'): ['Ireland'],
 ('2017-05-28',
  'Dot',
  'Siebenthal',
  'dsiebenthal@codingtemple.com'): ['Ireland'],
 ('2017-05-28', 'Marget', 'Crossen', 'mcrossen@codingtemple.com'): ['Ireland'],
 ('2017-05-28',
  'Marie',
  'Bottenfield',
  'mbottenfield@codingtemple.com'): ['Ireland'],
 ('2017-05-28',
  'Riva',
  'Guldemond',
  'rguldemond@codingtemple.com'): ['Ireland'],
 ('2017-05-28',
  'Santos',
  'Terrence',
  'sterrence@codingtemple.com'): ['Ireland'],
 ('2017-05-31',
  'Patrick',
  'Pereyra',
  'ppereyra@codingtemple.com'): ['United Kingdom'],
 ('2017-05-31',
  'Tifany',
  'Brechbiel',
  'tbrechbiel@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Anisha',
  'Rosentrater',
  'arosentrater@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Bennett',
  'Kilcher',
  'bkilcher@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Celine',
  'Coryea',
  'ccoryea@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Deetta',
  'Needler',
  'dneedler@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Dina',
  'Allocca',
  'dallocca@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Eleanora',
  'Maohu',
  'emaohu@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Genaro',
  'Cintron',
  'gcintron@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'January',
  'Holtrop',
  'jholtrop@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Jasper',
  'Battistoni',
  'jbattistoni@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Jeremy',
  'Goettsche',
  'jgoettsche@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Linnie',
  'Sachez',
  'lsachez@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Natosha',
  'Behal',
  'nbehal@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Onita',
  'Stutler',
  'ostutler@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Sandy',
  'Szabo',
  'sszabo@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Sherise',
  'Maleck',
  'smaleck@codingtemple.com'): ['United Kingdom'],
 ('2017-06-01',
  'Shirleen',
  'Corlett',
  'scorlett@codingtemple.com'): ['United Kingdom'],
 ('2017-06-02',
  'Blossom',
  'Chiappetta',
  'bchiappetta@codingtemple.com'): ['Singapore'],
 ('2017-06-02', 'Broderick', 'Durke', 'bdurke@codingtemple.com'): ['France'],
 ('2017-06-02', 'Colette', 'Traut', 'ctraut@codingtemple.com'): ['Singapore'],
 ('2017-06-02', 'Evangeline', 'Geis', 'egeis@codingtemple.com'): ['Singapore'],
 ('2017-06-02',
  'Fanny',
  'Heiberger',
  'fheiberger@codingtemple.com'): ['Singapore'],
 ('2017-06-02',
  'Jaimie',
  'Molzahn',
  'jmolzahn@codingtemple.com'): ['Singapore'],
 ('2017-06-02',
  'Nenita',
  'Corporan',
  'ncorporan@codingtemple.com'): ['Singapore'],
 ('2017-06-02',
  'William',
  'Preast',
  'wpreast@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Daniella',
  'Maneafaiga',
  'dmaneafaiga@codingtemple.com'): ['France'],
 ('2017-06-03',
  'Dorine',
  'Haselhuhn',
  'dhaselhuhn@codingtemple.com'): ['Singapore'],
 ('2017-06-03', 'Harry', 'Boles', 'hboles@codingtemple.com'): ['Singapore'],
 ('2017-06-03', 'Isa', 'Moala', 'imoala@codingtemple.com'): ['Singapore'],
 ('2017-06-03', 'Jamar', 'Garafola', 'jgarafola@codingtemple.com'): ['France'],
 ('2017-06-03',
  'Jannet',
  'Novakovich',
  'jnovakovich@codingtemple.com'): ['Singapore'],
 ('2017-06-03', 'Jude', 'Kuester', 'jkuester@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Marjorie',
  'Skrobacki',
  'mskrobacki@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Patricia',
  'Rushford',
  'prushford@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Robbi',
  'Dreyfuss',
  'rdreyfuss@codingtemple.com'): ['Singapore'],
 ('2017-06-03', 'Sheron', 'Kriger', 'skriger@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Shondra',
  'Gallardo',
  'sgallardo@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Veta',
  'Goldhirsh',
  'vgoldhirsh@codingtemple.com'): ['Singapore'],
 ('2017-06-03',
  'Yesenia',
  'Niedzwiecki',
  'yniedzwiecki@codingtemple.com'): ['Singapore'],
 ('2017-06-04',
  'Evelina',
  'Cantatore',
  'ecantatore@codingtemple.com'): ['France'],
 ('2017-06-04',
  'Hope',
  'Harrah',
  'hharrah@codingtemple.com'): ['United Kingdom'],
 ('2017-06-04',
  'Jung',
  'Schouten',
  'jschouten@codingtemple.com'): ['United Kingdom'],
 ('2017-06-04',
  'Lakiesha',
  'Cobian',
  'lcobian@codingtemple.com'): ['United Kingdom'],
 ('2017-06-04',
  'Noe',
  'Rilley',
  'nrilley@codingtemple.com'): ['United Kingdom'],
 ('2017-06-04', 'Noma', 'Beau', 'nbeau@codingtemple.com'): ['France'],
 ('2017-06-04',
  'Rozanne',
  'Tilleman',
  'rtilleman@codingtemple.com'): ['United Kingdom'],
 ('2017-06-04', 'Thaddeus', 'Grush', 'tgrush@codingtemple.com'): ['France'],
 ('2017-06-04', 'Winona', 'Kissner', 'wkissner@codingtemple.com'): ['France'],
 ('2017-06-05', 'Agripina', 'Passi', 'apassi@codingtemple.com'): ['Ireland'],
 ('2017-06-05',
  'Benton',
  'Merrithew',
  'bmerrithew@codingtemple.com'): ['France'],
 ('2017-06-05',
  'Jaimee',
  'Helland',
  'jhelland@codingtemple.com'): ['Singapore'],
 ('2017-06-05', 'Tamra', 'Gilgour', 'tgilgour@codingtemple.com'): ['France'],
 ('2017-06-06', 'Andrew', 'Waloven', 'awaloven@codingtemple.com'): ['France'],
 ('2017-06-06',
  'Astrid',
  'Latulipe',
  'alatulipe@codingtemple.com'): ['France'],
 ('2017-06-06',
  'Hassan',
  'Scheiern',
  'hscheiern@codingtemple.com'): ['France'],
 ('2017-06-06',
  'Jacqualine',
  'Macareno',
  'jmacareno@codingtemple.com'): ['France'],
 ('2017-06-06', 'Janita', 'Topp', 'jtopp@codingtemple.com'): ['France'],
 ('2017-06-06', 'Joseph', 'Defore', 'jdefore@codingtemple.com'): ['France'],
 ('2017-06-06', 'Latrisha', 'Haymer', 'lhaymer@codingtemple.com'): ['France'],
 ('2017-06-06', 'Leon', 'Fears', 'lfears@codingtemple.com'): ['Singapore'],
 ('2017-06-06', 'Lewis', 'Percey', 'lpercey@codingtemple.com'): ['Singapore'],
 ('2017-06-06', 'Sam', 'Steffey', 'ssteffey@codingtemple.com'): ['France'],
 ('2017-06-06', 'Sunday', 'Tukis', 'stukis@codingtemple.com'): ['France'],
 ('2017-06-06', 'Trula', 'Pinela', 'tpinela@codingtemple.com'): ['France'],
 ('2017-06-08', 'Amina', 'Gimble', 'agimble@codingtemple.com'): ['France'],
 ('2017-06-08', 'Carmon', 'Sibille', 'csibille@codingtemple.com'): ['France'],
 ('2017-06-08', 'Doretta', 'Vosburg', 'dvosburg@codingtemple.com'): ['France'],
 ('2017-06-08', 'Ericka', 'Fallick', 'efallick@codingtemple.com'): ['France'],
 ('2017-06-08', 'Julieann', 'Effner', 'jeffner@codingtemple.com'): ['France'],
 ('2017-06-08', 'Vern', 'Rindal', 'vrindal@codingtemple.com'): ['France'],
 ('2017-06-09', 'Carlos', 'Grasso', 'cgrasso@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Carlton',
  'Whichard',
  'cwhichard@codingtemple.com'): ['Singapore'],
 ('2017-06-09',
  'Chanell',
  'Kollmorgen',
  'ckollmorgen@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Darcel', 'Rede', 'drede@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Florrie', 'Peteet', 'fpeteet@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Henry', 'Vazzana', 'hvazzana@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Kandis',
  'Birenbaum',
  'kbirenbaum@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Laurette', 'Aubrey', 'laubrey@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Leatha', 'Alway', 'lalway@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Lynette', 'Nikolas', 'lnikolas@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Mao', 'Pittard', 'mpittard@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Maren', 'Leckband', 'mleckband@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Orpha',
  'Blackwelder',
  'oblackwelder@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Sharleen',
  'Kizior',
  'skizior@codingtemple.com'): ['Singapore'],
 ('2017-06-09', 'Sidney', 'Mallet', 'smallet@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Stephania',
  'Koellmann',
  'skoellmann@codingtemple.com'): ['Japan'],
 ('2017-06-09', 'Tomas', 'House', 'thouse@codingtemple.com'): ['Japan'],
 ('2017-06-09',
  'Vergie',
  'Abruzzese',
  'vabruzzese@codingtemple.com'): ['Singapore'],
 ('2017-06-09', 'Vernie', 'Cortner', 'vcortner@codingtemple.com'): ['Japan'],
 ('2017-06-10',
  'Gussie',
  'Barvosa',
  'gbarvosa@codingtemple.com'): ['United Kingdom'],
 ('2017-06-10', 'Stephnie', 'Riola', 'sriola@codingtemple.com'): ['Singapore'],
 ('2017-06-10',
  'Suellen',
  'Slupe',
  'sslupe@codingtemple.com'): ['United Kingdom'],
 ('2017-06-10',
  'Yajaira',
  'Pherigo',
  'ypherigo@codingtemple.com'): ['United Kingdom'],
 ('2017-06-11',
  'Chery',
  'Sultemeier',
  'csultemeier@codingtemple.com'): ['Japan'],
 ('2017-06-11', 'Coral', 'Codell', 'ccodell@codingtemple.com'): ['Japan'],
 ('2017-06-11', 'Dorthy', 'Vates', 'dvates@codingtemple.com'): ['Singapore'],
 ('2017-06-11',
  'Eladia',
  'Allscheid',
  'eallscheid@codingtemple.com'): ['Japan'],
 ('2017-06-11', 'Fiona', 'Sylvis', 'fsylvis@codingtemple.com'): ['Japan'],
 ('2017-06-11', 'Maye', 'Eby', 'meby@codingtemple.com'): ['Japan'],
 ('2017-06-11',
  'Tommye',
  'Henrickson',
  'thenrickson@codingtemple.com'): ['Japan'],
 ('2017-06-12', 'Cindi', 'Malakan', 'cmalakan@codingtemple.com'): ['France'],
 ('2017-06-12', 'Dora', 'Gezalyan', 'dgezalyan@codingtemple.com'): ['Japan'],
 ('2017-06-13', 'Shannon', 'Cowgill', 'scowgill@codingtemple.com'): ['Japan'],
 ('2017-06-14', 'Winter', 'Dolinger', 'wdolinger@codingtemple.com'): ['Japan'],
 ('2017-06-19', 'Lilian', 'Tacadina', 'ltacadina@codingtemple.com'): ['Japan'],
 ('2017-06-21', 'Monroe', 'Anhalt', 'manhalt@codingtemple.com'): ['France'],
 ('2017-06-22', 'Annett', 'Bending', 'abending@codingtemple.com'): ['Canada'],
 ('2017-06-22',
  'Katherine',
  'Schoeman',
  'kschoeman@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Antwan', 'Gewant', 'agewant@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Carol', 'Sabori', 'csabori@codingtemple.com'): ['Canada'],
 ('2017-06-23',
  'Edris',
  'Lizarrago',
  'elizarrago@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Evie', 'Hartly', 'ehartly@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Joni', 'Trieger', 'jtrieger@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Lin', 'Gritton', 'lgritton@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Marco', 'Hutley', 'mhutley@codingtemple.com'): ['Canada'],
 ('2017-06-23',
  'Markus',
  'Anglebrandt',
  'manglebrandt@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Natividad', 'Shier', 'nshier@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Randy', 'Rojero', 'rrojero@codingtemple.com'): ['Canada'],
 ('2017-06-23',
  'Richard',
  'Radoslovich',
  'rradoslovich@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Roseline', 'Veyna', 'rveyna@codingtemple.com'): ['Canada'],
 ('2017-06-23', 'Toccara', 'Devoll', 'tdevoll@codingtemple.com'): ['Canada'],
 ('2017-06-25', 'Xuan', 'Lubbert', 'xlubbert@codingtemple.com'): ['Canada'],
 ('2017-06-28', 'Brandon', 'Ludeker', 'bludeker@codingtemple.com'): ['Canada'],
 ('2017-06-28', 'Winston', 'Faines', 'wfaines@codingtemple.com'): ['Canada'],
 ('2017-06-29',
  'Meghan',
  'Manusyants',
  'mmanusyants@codingtemple.com'): ['Canada'],
 ('2017-06-29',
  'Pearly',
  'Salowitz',
  'psalowitz@codingtemple.com'): ['Canada'],
 ('2017-06-30', 'Matthew', 'Nealer', 'mnealer@codingtemple.com'): ['Canada'],
 ('2017-06-30',
  'Noella',
  'Peragine',
  'nperagine@codingtemple.com'): ['Canada'],
 ('2017-06-30', 'Peter', 'Curt', 'pcurt@codingtemple.com'): ['Canada'],
 ('2017-07-03',
  'Mellie',
  'Boyarski',
  'mboyarski@codingtemple.com'): ['Canada']}

In [60]:
sorted2 = df.sort_values(by=['partners/availableDates/0', 'partners/availableDates/1', 'partners/availableDates/2', 'partners/availableDates/3', 'partners/availableDates/4', 'partners/availableDates/5', 'partners/availableDates/6', 'partners/availableDates/7', 'partners/availableDates/8', 'partners/country', 'partners/email', 'partners/firstName', 'partners/lastName', 'partners/availableDates/9', 'partners/availableDates/10', 'partners/availableDates/11', 'partners/availableDates/12'])
pd.set_option('display.max_rows', 500)
sorted2

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

,partners/availableDates/0,partners/availableDates/1,partners/availableDates/2,partners/availableDates/3,partners/availableDates/4,partners/availableDates/5,partners/availableDates/6,partners/availableDates/7,partners/availableDates/8,partners/country,partners/email,partners/firstName,partners/lastName,partners/availableDates/9,partners/availableDates/10,partners/availableDates/11,partners/availableDates/12
51,2017-04-15,2017-04-16,2017-04-17,2017-04-18,2017-04-23,2017-04-24,2017-04-26,2017-04-27,2017-05-03,Spain,oduttinger@codingtemple.com,Obdulia,Duttinger,2017-05-04,NaN,NaN,NaN
56,2017-04-15,2017-04-16,2017-04-17,2017-04-18,2017-04-23,2017-04-24,2017-04-28,2017-04-29,2017-05-03,Spain,cbrookhouse@codingtemple.com,Caprice,Brookhouse,2017-05-04,2017-05-06,NaN,NaN
57,2017-04-15,2017-04-16,2017-04-17,2017-04-18,2017-04-23,2017-04-27,2017-04-29,2017-04-30,2017-05-02,Spain,mselk@codingtemple.com,Marcela,Selk,2017-05-03,2017-05-04,NaN,NaN
66,2017-04-15,2017-04-16,2017-04-17,2017-04-18,2017-04-24,2017-04-29,2017-05-01,2017-05-02,2017-05-03,Spain,civery@codingtemple.com,Camie,Ivery,2017-05-04,NaN,NaN,NaN
55,2017-04-15,2017-04-16,2017-04-17,2017-04-23,2017-04-28,2017-04-29,2017-05-01,2017-05-03,2017-05-04,Spain,aferkovich@codingtemple.com,Alleen,Ferkovich,NaN,NaN,NaN,NaN
62,2017-04-15,2017-04-16,2017-04-17,2017-04-26,2017-04-27,2017-04-29,2017-04-30,2017-05-02,2017-05-03,Spain,labbot@codingtemple.com,Loree,Abbot,2017-05-04,NaN,NaN,NaN
60,2017-04-15,2017-04-16,2017-04-17,2017-05-02,2017-05-03,2017-05-04,2017-05-08,NaN,NaN,Spain,devora@codingtemple.com,Dick,Evora,NaN,NaN,NaN,NaN
73,2017-04-15,2017-04-18,2017-04-23,2017-04-26,2017-04-28,2017-05-01,2017-05-02,2017-05-07,NaN,Spain,jfavieri@codingtemple.com,Jenee,Favieri,NaN,NaN,NaN,NaN
74,2017-04-15,2017-04-19,2017-04-23,2017-04-26,2017-05-01,2017-05-02,NaN,NaN,NaN,Spain,sstudniarz@codingtemple.com,Sima,Studniarz,NaN,NaN,NaN,NaN
64,2017-04-16,2017-04-17,2017-04-18,2017-04-19,2017-04-23,2017-04-27,2017-05-02,2017-05-03,2017-05-04,Spain,vodien@codingtemple.com,Venus,Odien,2017-05-08,NaN,NaN,NaN
61,2017-04-16,2017-04-17,2017-04-18,2017-04-22,2017-04-23,2017-04-24,2017-04-28,2017-04-29,2017-05-02,Spain,bcustis@codingtemple.com,Bronwyn,Custis,2017-05-03,2017-05-04,NaN,NaN
59,2017-04-16,2017-04-17,2017-04-18,2017-04-23,2017-04-24,2017-04-26,2017-05-01,2017-05-02,2017-05-03,Spain,jplants@codingtemple.com,Jen,Plants,2017-05-04,NaN,NaN,NaN
67,2017-04-16,2017-04-17,2017-04-18,2017-04-27,2017-04-28,2017-05-03,2017-05-04,NaN,NaN,Spain,dheckler@codingtemple.com,Dorie,Heckler,NaN,NaN,NaN,NaN
65,2017-04-16,2017-04-17,2017-04-18,2017-04-27,2017-05-02,2017-05-03,2017-05-04,NaN,NaN,Spain,alema@codingtemple.com,Angelita,Lema,NaN,NaN,NaN,NaN
58,2017-04-16,2017-04-17,2017-04-19,2017-04-20,2017-04-27,2017-05-02,2017-05-03,2017-05-04,NaN,Spain,amacneil@codingtemple.com,Allena,Macneil,NaN,NaN,NaN,NaN
53,2017-04-16,2017-04-17,2017-04-19,2017-04-23,2017-04-26,2017-04-27,2017-04-28,2017-04-29,2017-05-02,Spain,alyme@codingtemple.com,Antonina,Lyme,2017-05-03,2017-05-04,NaN,NaN
63,2017-04-16,2017-04-17,2017-04-21,2017-04-22,2017-04-23,2017-04-26,2017-04-29,2017-05-03,2017-05-04,Spain,oalampi@codingtemple.com,Otha,Alampi,NaN,NaN,NaN,NaN
54,2017-04-16,2017-04-17,2017-04-24,2017-04-25,2017-04-27,2017-04-29,2017-04-30,2017-05-03,2017-05-04,Spain,mtalton@codingtemple.com,Mechelle,Talton,NaN,NaN,NaN,NaN
52,2017-04-16,2017-04-17,2017-04-28,2017-05-01,2017-05-02,2017-05-03,2017-05-04,NaN,NaN,Spain,tzavesky@codingtemple.com,Twila,Zavesky,NaN,NaN,NaN,NaN
83,2017-04-17,2017-04-19,2017-04-20,2017-04-21,2017-04-23,2017-04-25,2017-04-28,2017-04-29,2017-04-30,Mexico,otreworgy@codingtemple.com,Olivia,Treworgy,2017-05-04,2017-05-05,NaN,NaN
82,2017-04-17,2017-04-19,2017-04-20,2017-04-22,2017-04-27,2017-04-29,2017-04-30,2017-05-04,2017-05-05,Mexico,adanza@codingtemple.com,Alfonso,Danza,2017-05-06,2017-05-08,2017-05-10,NaN
78,2017-04-17,2017-04-19,2017-04-20,2017-04-24,2017-04-28,2017-04-29,2017-04-30,2017-05-01,2017-05-04,Mexico,sbrugliera@codingtemple.com,Sharon,Brugliera,2017-05-05,2017-05-06,NaN,NaN
91,2017-04-17,2017-04-19,2017-04-20,2017-04-25,2017-04-27,2017-04-29,2017-05-02,2017-05-04,2017-05-05,Mexico,fmaier@codingtemple.com,Florencia,Maier,NaN,NaN,NaN,NaN
84,2017-04-17,2017-04-19,2017-04-20,2017-04-25,2017-04-28,2017-04-29,2017-05-01,2017-05-04,2017-05-05,Mexico,bparmele@codingtemple.com,Bobbie,Parmele,2017-05-06,2017-05-09,NaN,NaN
89,2017-04-17,2017-04-19,2017-04-20,2017-04-30,2017-05-04,2017-05-05,2017-05-06,NaN,NaN,Mexico,amolinini@codingtemple.com,Artie,Molinini,NaN,NaN,NaN,NaN
102,2017-04-17,2017-04-21,2017-04-25,2017-04-28,2017-04-29,2017-04-30,2017-05-01,NaN,NaN,Mexico,breatherford@codingtemple.com,Billie,Reatherford,NaN,NaN,NaN,NaN
93,2017-04-17,2017-04-22,2017-04-24,2017-04-28,NaN,NaN,NaN,NaN,NaN,Mexico,pstrohbehn@codingtemple.com,Paulina,Strohbehn,NaN,NaN,NaN,NaN
96,2017-04-17,2017-04-22,2017-05-02,NaN,NaN,NaN,NaN,NaN,NaN,Mexico,cvipond@codingtemple.com,Celine,Vipond,NaN,NaN,NaN,NaN
80,2017-04-18,2017-04-19,2017-04-20,2017-04-25,2017-04-29,2017-04-30,2017-05-03,2017-05-04,2017-05-05,Mexico,ltoepperwein@codingtemple.com,Lazaro,Toepperwein,NaN,NaN,NaN,NaN
95,2017-04-18,2017-04-22,2017-04-25,2017-04-27,2017-04-29,2017-05-01,2017-05-03,2017-05-06,NaN,Mexico,svecchione@codingtemple.com,Sara,Vecchione,NaN,NaN,NaN,NaN
70,2017-04-18,2017-04-24,2017-04-25,2017-04-28,2017-04-29,NaN,NaN,NaN,NaN,Spain,bmcgue@codingtemple.com,Blake,Mcgue,NaN,NaN,NaN,NaN
75,2017-04-18,2017-04-26,2017-04-27,2017-04-28,2017-04-29,NaN,NaN,NaN,NaN,Spain,ohindman@codingtemple.com,Otilia,Hindman,NaN,NaN,NaN,NaN
88,2017-04-19,2017-04-20,2017-04-21,2017-04-22,2017-04-23,2017-04-28,2017-04-30,2017-05-04,2017-05-05,Mexico,vchenevert@codingtemple.com,Vonnie,Chenevert,NaN,NaN,NaN,NaN
69,2017-04-19,2017-04-20,2017-04-21,2017-04-23,2017-04-24,2017-04-26,2017-04-29,NaN,NaN,Spain,npleasanton@codingtemple.com,Nenita,Pleasanton,NaN,NaN,NaN,NaN
81,2017-04-19,2017-04-20,2017-04-22,2017-04-23,2017-04-25,2017-04-28,2017-05-02,2017-05-03,2017-05-04,Mexico,faceveda@codingtemple.com,Florene,Aceveda,2017-05-05,2017-05-06,NaN,NaN
92,2017-04-19,2017-04-20,2017-04-22,2017-04-23,2017-04-29,2017-05-02,2017-05-04,2017-05-05,2017-05-06,Mexico,bkuligowski@codingtemple.com,Bobby,Kuligowski,NaN,NaN,NaN,NaN
86,2017-04-19,2017-04-20,2017-04-22,2017-04-25,2017-04-26,2017-04-28,2017-04-30,2017-05-04,2017-05-05,Mexico,ymikhaiel@codingtemple.com,Youlanda,Mikhaiel,2017-05-06,NaN,NaN,NaN
79,2017-04-19,2017-04-20,2017-04-24,2017-04-25,2017-05-01,2017-05-03,2017-05-04,2017-05-05,2017-05-06,Mexico,crupprecht@codingtemple.com,Cameron,Rupprecht,2017-05-11,NaN,NaN,NaN
85,2017-04-19,2017-04-20,2017-04-24,2017-04-26,2017-05-04,2017-05-05,2017-05-06,NaN,NaN,Mexico,ghilkert@codingtemple.com,Glennie,Hilkert,NaN,NaN,NaN,NaN
87,2017-04-19,2017-04-20,2017-04-28,2017-04-30,2017-05-04,2017-05-05,NaN,NaN,NaN,Mexico,mdelarme@codingtemple.com,Merissa,Delarme,NaN,NaN,NaN,NaN
90,2017-04-19,2017-04-20,2017-04-29,2017-05-04,2017-05-05,NaN,NaN,NaN,NaN,Mexico,triopel@codingtemple.com,Toni,Riopel,NaN,NaN,NaN,NaN
71,2017-04-21,2017-04-22,2017-04-24,2017-04-27,2017-04-29,2017-05-02,2017-05-06,NaN,NaN,Spain,cwalbright@codingtemple.com,Caprice,Walbright,NaN,NaN,NaN,NaN
97,2017-04-21,2017-04-30,2017-05-02,2017-05-06,NaN,NaN,NaN,NaN,NaN,Mexico,kscarboro@codingtemple.com,Ken,Scarboro,NaN,NaN,NaN,NaN
100,2017-04-23,2017-04-24,2017-04-25,2017-04-28,2017-05-03,2017-05-09,NaN,NaN,NaN,Mexico,ksinitiere@codingtemple.com,Kathrin,Sinitiere,NaN,NaN,NaN,NaN
72,2017-04-24,2017-04-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,lhalmstead@codingtemple.com,Latrice,Halmstead,NaN,NaN,NaN,NaN
98,2017-04-24,2017-04-27,2017-04-28,2017-04-29,2017-05-01,2017-05-02,NaN,NaN,NaN,Mexico,jiacobelli@codingtemple.com,Jodee,Iacobelli,NaN,NaN,NaN,NaN
99,2017-04-25,2017-04-29,2017-04-30,NaN,NaN,NaN,NaN,NaN,NaN,Mexico,sjohannes@codingtemple.com,Sean,Johannes,NaN,NaN,NaN,NaN
76,2017-04-27,2017-04-29,2017-04-30,NaN,NaN,NaN,NaN,NaN,NaN,Spain,skampa@codingtemple.com,Shamika,Kampa,NaN,NaN,NaN,NaN
101,2017-04-28,2017-04-29,2017-05-06,NaN,NaN,NaN,NaN,NaN,NaN,Mexico,fhurlebaus@codingtemple.com,Floria,Hurlebaus,NaN,NaN,NaN,NaN
94,2017-04-28,2017-05-01,2017-05-06,2017-05-08,NaN,NaN,NaN,NaN,NaN,Mexico,olavine@codingtemple.com,Olinda,Lavine,NaN,NaN,NaN,NaN
77,2017-04-28,2017-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,anickless@codingtemple.com,Adriane,Nickless,NaN,NaN,NaN,NaN
68,2017-05-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spain,sloux@codingtemple.com,Shayne,Loux,NaN,NaN,NaN,NaN
18,2017-05-16,2017-05-17,2017-05-18,2017-05-19,2017-05-23,2017-05-24,2017-05-26,2017-05-31,2017-06-01,United States,fcragin@codingtemple.com,Felicita,Cragin,2017-06-07,NaN,NaN,NaN
5,2017-05-16,2017-05-18,2017-05-19,2017-05-20,2017-05-22,2017-05-23,2017-05-25,2017-05-28,2017-05-29,United States,msoult@codingtemple.com,Melvin,Soult,2017-06-01,2017-06-02,2017-06-03,NaN
15,2017-05-16,2017-05-19,2017-05-21,2017-05-26,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,United States,mvirgel@codingtemple.com,Maggie,Virgel,NaN,NaN,NaN,NaN
3,2017-05-16,2017-05-21,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,NaN,NaN,United States,eomersa@codingtemple.com,Ester,Omersa,NaN,NaN,NaN,NaN
9,2017-05-16,2017-05-22,2017-05-24,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-06-02,2017-06-03,United States,jmasher@codingtemple.com,Jeremiah,Masher,NaN,NaN,NaN,NaN
11,2017-05-17,2017-05-18,2017-05-19,2017-05-21,2017-05-25,2017-05-28,2017-05-29,2017-05-31,2017-06-01,United States,mmottern@codingtemple.com,Meta,Mottern,2017-06-02,2017-06-03,2017-06-06,NaN
19,2017-05-17,2017-05-19,2017-05-22,2017-05-25,2017-05-26,NaN,NaN,NaN,NaN,United States,sdockal@codingtemple.com,Shakita,Dockal,NaN,NaN,NaN,NaN
20,2017-05-17,2017-05-21,2017-05-23,2017-05-24,2017-05-25,2017-05-26,2017-06-09,NaN,NaN,United States,rbreznay@codingtemple.com,Robbyn,Breznay,NaN,NaN,NaN,NaN
25,2017-05-18,2017-05-19,2017-05-24,2017-05-25,2017-05-30,2017-05-31,2017-06-01,NaN,NaN,United States,hpolitte@codingtemple.com,Hans,Politte,NaN,NaN,NaN,NaN
21,2017-05-18,2017-05-19,2017-06-01,NaN,NaN,NaN,NaN,NaN,NaN,United States,dbelgrave@codingtemple.com,Donny,Belgrave,NaN,NaN,NaN,NaN
2,2017-05-18,2017-05-20,2017-05-21,2017-05-22,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-31,United States,mlacau@codingtemple.com,Merilyn,Lacau,2017-06-01,2017-06-02,2017-06-03,NaN
14,2017-05-18,2017-05-21,2017-05-22,2017-05-25,2017-05-28,2017-05-29,2017-06-02,2017-06-03,2017-06-08,United States,sbeemon@codingtemple.com,Shaunta,Beemon,2017-06-09,NaN,NaN,NaN
7,2017-05-18,2017-05-21,2017-05-23,2017-05-24,2017-05-26,2017-05-28,2017-05-29,2017-06-02,2017-06-03,United States,lsolid@codingtemple.com,Luna,Solid,NaN,NaN,NaN,NaN
23,2017-05-18,2017-05-21,2017-05-30,NaN,NaN,NaN,NaN,NaN,NaN,United States,sskinnen@codingtemple.com,Stacy,Skinnen,NaN,NaN,NaN,NaN
4,2017-05-18,2017-05-22,2017-05-25,2017-05-28,2017-05-29,2017-05-31,2017-06-01,2017-06-02,2017-06-03,United States,ssheahan@codingtemple.com,Shanna,Sheahan,NaN,NaN,NaN,NaN
24,2017-05-18,2017-05-24,2017-05-26,2017-05-31,2017-06-08,NaN,NaN,NaN,NaN,United States,lskeeters@codingtemple.com,Lanie,Skeeters,NaN,NaN,NaN,NaN
0,2017-05-19,2017-05-20,2017-05-21,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,rketring@codingtemple.com,Rebbeca,Ketring,NaN,NaN,NaN,NaN
22,2017-05-19,2017-05-21,2017-05-25,2017-06-01,NaN,NaN,NaN,NaN,NaN,United States,nkobbe@codingtemple.com,Nada,Kobbe,NaN,NaN,NaN,NaN
8,2017-05-19,2017-05-22,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,United States,bwatton@codingtemple.com,Britt,Watton,2017-06-02,2017-06-03,NaN,NaN
12,2017-05-19,2017-05-24,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,United States,pdougherty@codingtemple.com,Phung,Dougherty,NaN,NaN,NaN,NaN
10,2017-05-19,2017-05-24,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-06-02,2017-06-03,NaN,United States,afernadez@codingtemple.com,Aaron,Fernadez,NaN,NaN,NaN,NaN
17,2017-05-21,2017-05-22,2017-05-23,2017-05-31,2017-06-01,NaN,NaN,NaN,NaN,United States,jglosson@codingtemple.com,Jude,Glosson,NaN,NaN,NaN,NaN
16,2017-05-21,2017-05-24,2017-05-26,2017-05-31,NaN,NaN,NaN,NaN,NaN,United States,szenger@codingtemple.com,Soraya,Zenger,NaN,NaN,NaN,NaN
6,2017-05-22,2017-05-23,2017-05-26,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,NaN,United States,bleeks@codingtemple.com,Bong,Leeks,NaN,NaN,NaN,NaN
28,2017-05-24,2017-05-25,2017-05-27,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,Ireland,enawwar@codingtemple.com,Everette,Nawwar,2017-06-08,2017-06-14,NaN,NaN
37,2017-05-24,2017-05-25,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-04,2017-06-05,2017-06-08,Ireland,cscoby@codingtemple.com,Claude,Scoby,2017-06-11,NaN,NaN,NaN
34,2017-05-24,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-09,2017-06-11,Ireland,mclawson@codingtemple.com,Marva,Clawson,2017-06-16,NaN,NaN,NaN
47,2017-05-24,2017-05-26,2017-06-05,2017-06-11,NaN,NaN,NaN,NaN,NaN,Ireland,mcomer@codingtemple.com,Maryland,Comer,NaN,NaN,NaN,NaN
13,2017-05-24,2017-05-28,2017-05-29,2017-06-01,2017-06-02,2017-06-03,NaN,NaN,NaN,United States,sdegunya@codingtemple.com,Suzan,Degunya,NaN,NaN,NaN,NaN
42,2017-05-24,2017-06-01,2017-06-04,2017-06-05,2017-06-07,2017-06-09,NaN,NaN,NaN,Ireland,mkimble@codingtemple.com,Marinda,Kimble,NaN,NaN,NaN,NaN
41,2017-05-24,2017-06-01,2017-06-04,2017-06-11,NaN,NaN,NaN,NaN,NaN,Ireland,emullahy@codingtemple.com,Edith,Mullahy,NaN,NaN,NaN,NaN
50,2017-05-24,2017-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,kdickinson@codingtemple.com,Keisha,Dickinson,NaN,NaN,NaN,NaN
29,2017-05-25,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,2017-06-06,Ireland,pbertog@codingtemple.com,Paola,Bertog,2017-06-08,2017-06-15,NaN,NaN
45,2017-05-25,2017-05-26,2017-06-01,2017-06-11,NaN,NaN,NaN,NaN,NaN,Ireland,jlehoullier@codingtemple.com,Jerrod,Lehoullier,NaN,NaN,NaN,NaN
1,2017-05-25,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-02,2017-06-03,NaN,NaN,United States,ccafaro@codingtemple.com,Casey,Cafaro,NaN,NaN,NaN,NaN
44,2017-05-25,2017-06-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,mdolinsky@codingtemple.com,Margarita,Dolinsky,NaN,NaN,NaN,NaN
31,2017-05-26,2017-05-27,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-04,2017-06-07,2017-06-09,Ireland,rfarlee@codingtemple.com,Rosanne,Farlee,2017-06-11,NaN,NaN,NaN
36,2017-05-26,2017-05-27,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-07,2017-06-09,NaN,Ireland,akulju@codingtemple.com,Ali,Kulju,NaN,NaN,NaN,NaN
39,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,2017-06-06,2017-06-07,Ireland,dharriet@codingtemple.com,Dina,Harriet,2017-06-09,2017-06-11,NaN,NaN
32,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,2017-06-07,2017-06-11,Ireland,elaskin@codingtemple.com,Elliot,Laskin,2017-06-17,NaN,NaN,NaN
33,2017-05-26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-06,2017-06-11,NaN,NaN,Ireland,greif@codingtemple.com,Geneva,Reif,NaN,NaN,NaN,NaN
43,2017-05-26,2017-06-04,2017-06-07,2017-06-11,NaN,NaN,NaN,NaN,NaN,Ireland,mcodispoti@codingtemple.com,Marjorie,Codispoti,NaN,NaN,NaN,NaN
49,2017-05-26,2017-06-05,2017-06-07,2017-06-11,2017-06-14,NaN,NaN,NaN,NaN,Ireland,dtighe@codingtemple.com,Delmer,Tighe,NaN,NaN,NaN,NaN
46,2017-05-27,2017-06-01,2017-06-07,NaN,NaN,NaN,NaN,NaN,NaN,Ireland,jmanoso@codingtemple.com,Jerrica,Manoso,NaN,NaN,NaN,NaN
40,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,2017-06-05,2017-06-07,NaN,Ireland,mcrossen@codingtemple.com,Marget,Crossen,NaN,NaN,NaN,NaN
38,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-04,2017-06-11,2017-06-17,NaN,Ireland,dsiebenthal@codingtemple.com,Dot,Siebenthal,NaN,NaN,NaN,NaN
27,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-01,2017-06-06,2017-06-07,NaN,NaN,Ireland,dpatnode@codingtemple.com,Daniella,Patnode,NaN,NaN,NaN,NaN
35,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-04,2017-06-05,2017-06-06,2017-06-08,2017-06-09,Ireland,mbottenfield@codingtemple.com,Marie,Bottenfield,NaN,NaN,NaN,NaN
26,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-04,2017-06-05,NaN,NaN,NaN,Ireland,sterrence@codingtemple.com,Santos,Terrence,NaN,NaN,NaN,NaN
30,2017-05-28,2017-05-29,2017-05-30,2017-05-31,2017-06-07,2017-06-11,NaN,NaN,NaN,Ireland,rguldemond@codingtemple.com,Riva,Guldemond,NaN,NaN,NaN,NaN
201,2017-05-31,2017-06-04,2017-06-08,2017-06-10,2017-06-14,2017-06-15,2017-06-17,2017-06-18,NaN,United Kingdom,tbrechbiel@codingtemple.com,Tifany,Brechbiel,NaN,NaN,NaN,NaN
203,2017-05-31,2017-06-07,2017-06-10,2017-06-12,2017-06-14,2017-06-16,NaN,NaN,NaN,United Kingdom,ppereyra@codingtemple.com,Patrick,Pereyra,NaN,NaN,NaN,NaN
187,2017-06-01,2017-06-02,2017-06-03,2017-06-04,2017-06-05,2017-06-06,2017-06-14,2017-06-16,NaN,United Kingdom,ccoryea@codingtemple.com,Celine,Coryea,NaN,NaN,NaN,NaN
183,2017-06-01,2017-06-02,2017-06-04,2017-06-05,2017-06-06,2017-06-07,2017-06-14,NaN,NaN,United Kingdom,bkilcher@codingtemple.com,Bennett,Kilcher,NaN,NaN,NaN,NaN
182,2017-06-01,2017-06-02,2017-06-04,2017-06-05,2017-06-06,2017-06-13,NaN,NaN,NaN,United Kingdom,nbehal@codingtemple.com,Natosha,Behal,NaN,NaN,NaN,NaN
189,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-07,2017-06-10,2017-06-12,2017-06-13,2017-06-14,United Kingdom,scorlett@codingtemple.com,Shirleen,Corlett,2017-06-15,2017-06-16,2017-06-17,NaN
188,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-10,2017-06-12,2017-06-13,2017-06-17,United Kingdom,gcintron@codingtemple.com,Genaro,Cintron,2017-06-19,NaN,NaN,NaN
181,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-10,2017-06-12,2017-06-13,2017-06-18,United Kingdom,jgoettsche@codingtemple.com,Jeremy,Goettsche,2017-06-21,2017-06-22,NaN,NaN
191,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-10,2017-06-12,2017-06-21,NaN,United Kingdom,dneedler@codingtemple.com,Deetta,Needler,NaN,NaN,NaN,NaN
186,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-10,2017-06-13,2017-06-14,2017-06-17,United Kingdom,jbattistoni@codingtemple.com,Jasper,Battistoni,2017-06-23,NaN,NaN,NaN
184,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-12,2017-06-13,2017-06-15,2017-06-16,United Kingdom,ostutler@codingtemple.com,Onita,Stutler,2017-06-21,NaN,NaN,NaN
190,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-09,2017-06-12,2017-06-13,2017-06-17,NaN,United Kingdom,dallocca@codingtemple.com,Dina,Allocca,NaN,NaN,NaN,NaN
193,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-10,2017-06-16,2017-06-17,NaN,NaN,United Kingdom,sszabo@codingtemple.com,Sandy,Szabo,NaN,NaN,NaN,NaN
195,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-12,2017-06-13,2017-06-14,2017-06-17,NaN,United Kingdom,jholtrop@codingtemple.com,January,Holtrop,NaN,NaN,NaN,NaN
194,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-12,2017-06-14,2017-06-16,2017-06-17,2017-06-18,United Kingdom,smaleck@codingtemple.com,Sherise,Maleck,NaN,NaN,NaN,NaN
185,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-13,2017-06-14,2017-06-15,2017-06-17,NaN,United Kingdom,emaohu@codingtemple.com,Eleanora,Maohu,NaN,NaN,NaN,NaN
192,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-16,2017-06-17,NaN,NaN,NaN,United Kingdom,lsachez@codingtemple.com,Linnie,Sachez,NaN,NaN,NaN,NaN
180,2017-06-01,2017-06-02,2017-06-05,2017-06-06,2017-06-18,NaN,NaN,NaN,NaN,United Kingdom,arosentrater@codingtemple.com,Anisha,Rosentrater,NaN,NaN,NaN,NaN
128,2017-06-02,2017-06-03,2017-06-04,2017-06-05,2017-06-07,2017-06-08,2017-06-09,2017-06-11,2017-06-15,Singapore,bchiappetta@codingtemple.com,Blossom,Chiappetta,2017-06-16,2017-06-21,NaN,NaN
137,2017-06-02,2017-06-03,2017-06-04,2017-06-06,2017-06-07,2017-06-08,2017-06-09,2017-06-10,2017-06-11,Singapore,jmolzahn@codingtemple.com,Jaimie,Molzahn,2017-06-15,2017-06-19,NaN,NaN
133,2017-06-02,2017-06-03,2017-06-04,2017-06-06,2017-06-07,2017-06-08,2017-06-11,2017-06-12,2017-06-19,Singapore,ctraut@codingtemple.com,Colette,Traut,NaN,NaN,NaN,NaN

In [59]:
pd.set_option('display.max_rows', 500)